credentials:
  usernames:
    canberkaslan: # Bu kullanıcı adıdır
      email: canberklarslan@gmail.com
      name: Canberk Arslan # Bu görünecek isimdir
      password: 'Uniq2025.' # generate_keys.py ile oluşturulan hash'lenmiş şifre
    ikinci_kullanici:
      email: canbakirtel@uniqstore.com.tr
      name: Can Bakırtel
      password: 'Uniq2025.' # Başka bir hash'lenmiş şifre
cookie:
  expiry_days: 999
  key: 'some_random_signature_key' # Rastgele bir anahtar girin
  name: some_cookie_name
