credentials:
  usernames:
    canberkaslan: # Bu kullanıcı adıdır
      email: canberkarslan@uniqstore.com.tr
      name: Canberk Arslan # Bu görünecek isimdir
      password: '$2b$12$a63nUVspL4XrS57lF5KrMuSWgelhjKOPYI7xp7Kc1H/2enT52irDS' # generate_keys.py ile oluşturulan hash'lenmiş şifre
    ikinci_kullanici:
      email: canbakirtel@uniqstore.com.tr
      name: Can Bakırtel
      password: '$2b$12$a63nUVspL4XrS57lF5KrMuSWgelhjKOPYI7xp7Kc1H/2enT52irDS' # Başka bir hash'lenmiş şifre
cookie:
  expiry_days: 999
  key: 'some_random_signature_key' # Rastgele bir anahtar girin
  name: some_cookie_name
