credentials:
  usernames:
    stildiva: # Bu kullanıcı adıdır
      email: bilgi@uniqstore.com.tr
      name: Stil Diva # Bu görünecek isimdir
      password: '$2b$12$6NPO8Y/Kmp/6zbG49yPde.VgnMOB1Ju9OQhUQz9lmX1A/ti.HKsvK' # generate_keys.py ile oluşturulan hash'lenmiş şifre

cookie:
  expiry_days: 30
  key: some_random_key # Buradaki anahtarın gizli olduğundan emin olun
  name: some_cookie_name
