credentials:
  usernames:
    stildiva: # Bu kullanıcı adıdır
      email: bilgi@uniqstore.com.tr
      name: Uniq Store # Bu görünecek isimdir
      password: '$2b$12$E2scZ2J77gBaWfLGYf7hw.oZlopb9Sc5oqI16NhdAYoZH2lbVO0O.' # generate_keys.py ile oluşturulan hash'lenmiş şifre
      role: admin # Bu kullanıcının rolüdür
cookie:
  expiry_days: 999
  key: 'some_random_signature_key' # Rastgele bir anahtar girin
  name: some_cookie_name